--- #YAML:1.0
name:               App-Difio-dotCloud
version:            2.00
abstract:           Difio registration agent for dotCloud / Perl applications
author:
    - Alexander Todorov <atodorov@dif.io>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:                 0
    LWP::Protocol::https:  0
    LWP::UserAgent:       0
    Pod::Simple:          0
resources:
    bugtracker:  https://github.com/difio/difio-dotcloud-perl/issues
    homepage:    https://github.com/difio/difio-dotcloud-perl
    repository:  https://github.com/difio/difio-dotcloud-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
